#!/usr/bin/env bash

# description: This is a script to automatically deploy the about page

# The target directory is symlinked to
# the web root for nginx at /var/www/about.mediamajesty.com

# prerequisites: add a config file to the root of the project
# with the following variables:
# HOST="yourhost.com"
# USER="yourusername"
# DIR="yourdirectory"

source "config"
rsync -avz --delete about/ $USER@$HOST:~/$DIR

exit 0
