# Generated by Django 4.2.7 on 2024-01-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='media_url',
        ),
        migrations.AddField(
            model_name='item',
            name='media_file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]