# Generated by Django 4.2.7 on 2023-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
