# Generated by Django 4.2.7 on 2024-01-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_remove_item_media_url_item_media_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
