# Generated by Django 4.2.7 on 2024-01-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
