# Generated by Django 4.2.7 on 2024-01-21 20:42

import django.core.validators
from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_file',
            field=models.FileField(default=None, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'ogg', 'flac', 'pdf', 'doc', 'docx', 'txt']), items.models.validate_file_mime_type]),
        ),
    ]
