# Generated by Django 5.0.3 on 2024-03-16 09:49

import django.core.validators
import items.models
import storages.backends.azure_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_file',
            field=models.FileField(default=None, storage=storages.backends.azure_storage.AzureStorage(), upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi', 'mp3', 'wav', 'ogg', 'flac', 'pdf', 'doc', 'docx', 'txt']), items.models.validate_file_mime_type]),
        ),
    ]
